In [3]:
%%bash

mkdir -p ./data/
curl -L -o ./data/infoleg_vsm.tar.bz2 https://cs.famaf.unc.edu.ar/\~ccardellino/resources/infoleg/infoleg_vsm.tar.bz2
tar xvf ./data/infoleg_vsm.tar.bz2 -C ./data
rm -f ./data/infoleg_vsm.tar.bz2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 55.9M  100 55.9M    0     0   965k      0  0:00:59  0:00:59 --:--:-- 1829k
x infoleg_20window_flat.csv.gz
x infoleg_5window_scaled.csv.gz

In [4]:
import pandas as pd
infoleg_5window_scaled = pd.read_csv("./data/infoleg_5window_scaled.csv.gz", index_col=0)
infoleg_5window_scaled.head()

,"""",$,%,',(,),*,+,",",-,...,—,—en,‘,’,“,”,•,…,……,UNK
"""",188004.066667,1295.300000,1625.783333,369.766667,25640.866667,34281.000000,384.700000,109.533333,128313.183333,13480.766667,...,6763.500000,160.050000,242.883333,749.700000,24.116667,12.716667,775.066667,3158.016667,81.150000,0.200000
$,1295.300000,101943.100000,1659.450000,4.066667,78039.300000,41733.316667,409.350000,441.883333,14535.016667,4474.933333,...,166.333333,7.200000,15.800000,116.966667,1267.166667,969.200000,536.433333,834.183333,210.733333,1.533333
%,1625.783333,1659.450000,6677.033333,1.900000,42747.416667,69093.250000,458.416667,549.533333,20228.083333,2799.450000,...,338.250000,7.700000,10.983333,28.666667,515.283333,787.266667,707.433333,198.350000,22.783333,1.000000
',369.766667,4.066667,1.900000,811.400000,131.566667,706.616667,3.483333,2.500000,534.633333,108.116667,...,5.933333,0.000000,1.000000,3.516667,0.450000,0.000000,1.000000,0.750000,0.000000,0.250000
(,25640.866667,78039.300000,42747.416667,131.566667,25952.233333,572110.299999,6428.650000,1371.083333,205265.200001,33210.983333,...,7716.650000,73.933333,244.550000,830.833333,7284.766667,10580.500000,3220.850000,2191.000000,740.366667,1.000000